// config.js
module.exports = {
  TARGET_GROUP_ID: 'Cf36a100a627b9eafdd7c5e87fe3a88a6',
  CRON_SECRET: 'kesach2026secret',
  SCHEDULED_MESSAGES: {
    '1': 'Chào ngày mới Anh Chị, Chúc Anh Chị làm việc vui vẻ !',
    '2': 'Mình nhớ báo cáo Nhập Aba, Nhập Fresh, Kiểm Date, Kiểm Kê, In Tem Giá, Các công việc cơ bản trước 8h nhé !',
    '3': 'Mình có công việc báo cáo Fresh vào lúc 10h , Anh Chị nhớ hoàn tất nhé !',
    '4': 'Mình có công việc báo cáo Fresh vào nhóm siêu thị vào lúc 12h, Các nhóm Thu Ngân-Fresh Khu vực vào khung giờ này cũng cần báo cáo, Anh Chị nhớ hoàn tất nhé !',
    '5': 'Mình có công việc báo cáo Nộp Tiền trước 14h, Anh Chị nhớ hoàn tất nhé !',
    '6': 'Mình có công việc báo cáo Fresh vào lúc 14h, Anh Chị nhớ hoàn tất nhé !',
    '7': 'Mình có công việc báo cáo Fresh vào lúc 16h, Anh Chị nhớ hoàn tất nhé !',
    '8': 'Anh Chị cần kiểm tra và hoàn tất các công việc sau đây:\n\n1. Kiểm tra Tool CVST\n2. Kiểm tra hình ảnh  kệ phụ trách\n3. Kiểm tra đơn Online-Các vấn đề tiền\n4. Kiểm tra Fresh cuối ngày\n5. Vệ sinh Toilet\n\nCảm Ơn Anh Chị đã hoàn tất Cv cuối ngày!',
    '9': 'Chúc Anh Chị Ngủ Ngon! Nghĩ ngơi sớm nhé !',
  },

  DAY_LABELS: ['Chủ Nhật', 'Thứ 2', 'Thứ 3', 'Thứ 4', 'Thứ 5', 'Thứ 6', 'Thứ 7'],

  CLEANING_SCHEDULE: {
    0: ['Xuyên'],
    1: ['Biển'],
    2: ['Mai', 'Thi (Vệ sinh kho)', 'Vui/Ngọc (Trần nhà, Áp kính)'],
    3: ['Thư'],
    4: ['Tiên', 'Thi (Vệ sinh kho)', 'Vui/Ngọc (Trần nhà, Áp kính)'],
    5: ['Oanh'],
    6: ['Trường', 'Thi (Vệ sinh kho)', 'Vui/Ngọc (Trần nhà, Áp kính)'],
  },

  WEATHER_LOCATION: 'Sóc+Trăng',

  LIFE_QUOTES: [
    'Hãy sống mỗi ngày như thể đó là ngày cuối cùng, và học hỏi như thể sẽ sống mãi mãi.',
    'Cuộc sống không phải là chờ đợi cơn bão đi qua, mà là học cách nhảy múa dưới mưa.',
    'Hạnh phúc không phải là đích đến, mà là cách chúng ta đi trên hành trình đó.',
    'Mỗi buổi sáng là một cơ hội mới để bắt đầu lại và làm tốt hơn hôm qua.',
    'Nụ cười của bạn hôm nay có thể là ánh sáng dẫn đường cho ai đó.',
    'Đừng đếm những ngày trôi qua, hãy làm cho những ngày đó trở nên đáng giá.',
    'Thành công không phải là điểm cuối, thất bại không phải là kết thúc, quan trọng là sự dũng cảm để tiếp tục.',
    'Cuộc sống tươi đẹp hơn khi ta biết ơn những điều nhỏ bé quanh mình.',
    'Làm việc chăm chỉ hôm nay, để ngày mai được mỉm cười.',
    'Yêu thương những gì mình làm, mọi việc sẽ trở nên nhẹ nhàng hơn.',
    'Người thành công không phải người chưa từng vấp ngã, mà là người luôn đứng dậy sau mỗi lần vấp ngã.',
    'Đừng chờ đợi cơ hội, hãy tự mình tạo ra nó bằng chính sự chăm chỉ mỗi ngày.',
    'Một tinh thần lạc quan sẽ biến khó khăn thành cơ hội để trưởng thành.',
    'Gia đình là nơi bắt đầu mọi niềm vui và là bến đỗ bình yên sau mỗi ngày làm việc.',
    'Bí quyết để tiến xa là bắt đầu ngay từ hôm nay, dù chỉ là một bước nhỏ.',
    'Kỷ luật bản thân hôm nay chính là món quà bạn tặng cho chính mình ngày mai.',
    'Đừng sợ đi chậm, chỉ sợ đứng yên không tiến bước.',
    'Mỗi khó khăn đều mang theo một bài học, hãy đón nhận nó bằng nụ cười.',
    'Sự tử tế không tốn kém gì cả, nhưng giá trị của nó là vô giá.',
    'Người biết ơn là người luôn tìm thấy hạnh phúc dù trong hoàn cảnh nào.',
    'Thái độ tích cực chính là chìa khóa mở ra mọi cánh cửa thành công.',
    'Hãy làm việc bằng cả trái tim, thành quả sẽ tự nhiên đến.',
    'Không có con đường nào dẫn đến thành công mà không có mồ hôi và nỗ lực.',
    'Sống chậm lại một chút để cảm nhận những điều tốt đẹp quanh mình.',
    'Mỗi lần cố gắng, dù nhỏ, đều đưa bạn đến gần hơn với ước mơ.',
    'Niềm tin vào bản thân là nền tảng vững chắc nhất cho mọi thành công.',
    'Đoàn kết là sức mạnh, cùng nhau chúng ta sẽ đi được xa hơn.',
    'Hãy biến áp lực thành động lực để bứt phá mỗi ngày.',
    'Sự chân thành luôn được đền đáp bằng lòng tin và sự yêu mến.',
    'Ngày hôm nay là món quà, đó là lý do vì sao nó được gọi là hiện tại.',
    'Càng khó khăn, càng phải giữ vững tinh thần và nụ cười trên môi.',
    'Người mạnh mẽ không phải người không bao giờ khóc, mà là người biết đứng dậy sau nước mắt.',
    'Hãy trân trọng những gì mình đang có, vì đó là điều nhiều người ao ước.',
    'Chỉ cần bạn không bỏ cuộc, mọi cố gắng đều sẽ được đền đáp xứng đáng.',
    'Một ngày làm việc vui vẻ sẽ mang lại một đêm ngủ ngon và một ngày mai tươi sáng.',
    'Trách nhiệm và đam mê là hai đôi cánh giúp bạn bay cao trong công việc.',
    'Đừng so sánh mình với người khác, hãy so sánh mình hôm nay với chính mình hôm qua.',
    'Sự tận tâm trong công việc nhỏ sẽ mở đường cho những cơ hội lớn.',
    'Hãy luôn giữ cho mình một trái tim ấm áp giữa cuộc sống bộn bề.',
    'Niềm vui lớn nhất là khi thấy nỗ lực của mình mang lại giá trị cho người khác.',
    'Cuộc sống sẽ thưởng cho những ai kiên trì đến cùng.',
    'Một nụ cười chân thành có thể xoa dịu cả một ngày mệt mỏi.',
    'Hãy làm việc như thể không ai đang nhìn, và sống như thể mỗi ngày là món quà.',
    'Sự khiêm tốn và chăm chỉ luôn là nền tảng của những thành công bền vững.',
    'Đừng để nỗi sợ hãi ngăn cản bạn thử những điều mới mẻ.',
    'Mỗi sáng thức dậy là một cơ hội để viết tiếp câu chuyện đẹp của đời mình.',
    'Thành công không đến từ may mắn, mà đến từ sự chuẩn bị gặp cơ hội.',
    'Hãy đối xử với mọi người bằng sự tôn trọng, dù ở bất kỳ vị trí nào.',
    'Sự kiên nhẫn là chìa khóa để biến những điều không thể thành có thể.',
    'Một tập thể đoàn kết có thể vượt qua mọi thử thách khó khăn nhất.',
    'Đừng đợi ngày mai mới bắt đầu, hãy bắt đầu từ chính hôm nay.',
    'Mỗi giọt mồ hôi hôm nay là hạt giống cho thành quả ngày mai.',
    'Người lạc quan luôn tìm thấy cơ hội trong mọi khó khăn.',
    'Sự cố gắng không bao giờ phản bội kết quả.',
    'Hãy để nụ cười trở thành ngôn ngữ chung của mọi cuộc gặp gỡ.',
    'Cuộc đời như một chuyến đi, quan trọng không phải đích đến mà là những gì ta học được trên đường.',
    'Ai cũng có một ngày khó khăn, quan trọng là cách ta vượt qua nó.',
    'Thời gian không chờ đợi ai, hãy trân trọng từng khoảnh khắc.',
    'Một lời động viên đúng lúc có thể thay đổi cả ngày của một người.',
    'Đừng ngại bắt đầu lại, vì mỗi lần bắt đầu là một cơ hội mới.',
    'Sự tự tin đến từ sự chuẩn bị kỹ lưỡng, không phải từ may mắn.',
    'Hãy làm điều đúng, ngay cả khi không ai nhìn thấy.',
    'Người thành công biết biến trở ngại thành bàn đạp.',
    'Chăm chỉ là con đường ngắn nhất dẫn đến ước mơ.',
    'Hãy sống sao cho khi nhìn lại, bạn không phải hối tiếc.',
    'Một tập thể vững mạnh được xây dựng từ những cá nhân biết sẻ chia.',
    'Đừng để một ngày tồi tệ đánh gục cả một hành trình dài.',
    'Sự tử tế lan tỏa sẽ quay trở lại với bạn theo cách bất ngờ nhất.',
    'Hãy học cách buông bỏ những điều không thể thay đổi, và cố gắng hết mình với những điều có thể.',
    'Nỗ lực nhỏ mỗi ngày sẽ tạo nên thay đổi lớn theo thời gian.',
    'Người khôn ngoan học từ sai lầm của chính mình và của người khác.',
    'Bình tĩnh trước khó khăn là bước đầu để giải quyết vấn đề.',
    'Hãy trồng cây tử tế hôm nay để hái quả ngọt ngày sau.',
    'Có mục tiêu rõ ràng, con đường dù xa cũng sẽ đến đích.',
    'Thành công không phải là làm nhiều việc, mà là làm đúng việc.',
    'Một ngày mới là một trang giấy trắng, hãy viết nên điều tốt đẹp.',
    'Người mạnh mẽ không phải người không có nỗi sợ, mà là người dám đối mặt với nó.',
    'Hãy biết ơn cả những thử thách, vì chúng giúp ta trưởng thành.',
    'Nụ cười là chi phí thấp nhất mang lại giá trị cao nhất.',
    'Sự chân thành sẽ luôn được người khác cảm nhận và trân trọng.',
    'Đừng chờ điều kiện hoàn hảo mới hành động, hãy hành động rồi hoàn thiện dần.',
    'Hạnh phúc không phải có được mọi thứ, mà là biết đủ với những gì mình có.',
    'Người biết lắng nghe luôn học được nhiều hơn người chỉ biết nói.',
    'Mỗi thất bại là một bài học được trả bằng kinh nghiệm quý giá.',
    'Hãy làm việc với tinh thần trách nhiệm, kết quả sẽ tự nói lên tất cả.',
    'Đoàn kết giúp những điều tưởng chừng không thể trở thành có thể.',
    'Sống tích cực không có nghĩa là không có khó khăn, mà là biết cách vượt qua nó với nụ cười.',
    'Kiên trì là chìa khóa mở mọi cánh cửa mà tài năng không thể mở.',
    'Đừng sợ chậm, chỉ sợ dừng lại giữa chừng.',
    'Một người quản lý giỏi là người biết truyền cảm hứng cho cả đội ngũ.',
    'Hãy trân trọng đồng đội, vì thành công không bao giờ đến từ một mình.',
    'Cuộc sống công bằng với những ai không ngừng cố gắng.',
    'Người có tâm luôn được người khác tin tưởng và yêu mến.',
    'Sự khác biệt giữa thành công và thất bại đôi khi chỉ là một lần thử thêm.',
    'Hãy để mỗi ngày làm việc là một bước tiến, dù nhỏ, hướng về ước mơ.',
    'Niềm tin vào chính mình là nửa chặng đường của thành công.',
    'Đừng ngừng học hỏi, vì kiến thức là tài sản không ai lấy đi được.',
    'Một môi trường làm việc vui vẻ giúp mọi người phát huy hết khả năng.',
    'Hãy đối xử với khách hàng như đối xử với người thân trong gia đình.',
    'Chất lượng công việc phản ánh sự tôn trọng ta dành cho chính mình.',
    'Người biết cho đi thường nhận lại nhiều hơn những gì họ tưởng.',
    'Hãy giữ vững tinh thần dù ngày làm việc có bận rộn đến đâu.',
    'Sự chuẩn bị kỹ càng hôm nay giúp ta tự tin đối mặt với ngày mai.',
    'Thành quả ngọt ngào nhất luôn đến sau những nỗ lực bền bỉ nhất.',
    'Đừng để sự mệt mỏi làm mờ đi mục tiêu ban đầu của bạn.',
    'Mỗi khách hàng hài lòng là một lời cảm ơn dành cho sự cố gắng của cả đội.',
    'Hãy làm việc thông minh, nhưng đừng quên làm việc chăm chỉ.',
    'Người giỏi không phải người không mắc lỗi, mà là người sửa lỗi nhanh nhất.',
    'Sự chủ động luôn mang lại nhiều cơ hội hơn sự chờ đợi.',
    'Hãy coi mỗi khó khăn là một bài kiểm tra để ta trưởng thành hơn.',
    'Tinh thần đồng đội là nền tảng của mọi thành công lâu dài.',
    'Đừng để một sai lầm nhỏ làm bạn quên đi những thành công đã có.',
    'Hãy sống chậm lại để yêu thương nhiều hơn.',
    'Người hạnh phúc là người biết hài lòng với hiện tại và nỗ lực cho tương lai.',
    'Sự kiên định trong mục tiêu sẽ dẫn ta vượt qua mọi trở ngại.',
    'Hãy nhớ rằng mỗi ngày làm việc chăm chỉ là một viên gạch xây nên tương lai.',
    'Người thành công luôn tìm cách, người thất bại luôn tìm lý do.',
    'Đừng để nỗi lo hôm nay đánh cắp niềm vui của bạn.',
    'Hãy trao đi yêu thương, vì đó là thứ duy nhất càng cho càng nhiều.',
    'Sự trung thực luôn là nền tảng vững chắc nhất cho mọi mối quan hệ.',
    'Một tập thể mạnh là tập thể biết cùng nhau vượt khó.',
    'Hãy nhìn về phía trước, nhưng đừng quên trân trọng những gì đã qua.',
    'Người khiêm tốn luôn học được nhiều điều mới mỗi ngày.',
    'Đừng ngại hỏi khi chưa hiểu, vì hiểu rõ là bước đầu để làm tốt.',
    'Sự nỗ lực không ngừng nghỉ sẽ biến giấc mơ thành hiện thực.',
    'Hãy để mỗi lời nói của bạn mang theo sự ấm áp và chân thành.',
    'Người biết ơn cuộc sống sẽ luôn tìm thấy lý do để mỉm cười.',
    'Đừng để áp lực công việc làm bạn quên đi sức khỏe của chính mình.',
    'Hãy dành thời gian chăm sóc bản thân, vì bạn xứng đáng được yêu thương.',
    'Một nụ cười đầu ngày có thể lan tỏa năng lượng tích cực cho cả nhóm.',
    'Người kiên nhẫn luôn đạt được nhiều hơn người vội vàng.',
    'Hãy tin rằng mọi nỗ lực đều có ý nghĩa, dù kết quả chưa đến ngay.',
    'Sự tôn trọng lẫn nhau là chìa khóa của một tập thể đoàn kết.',
    'Đừng quên cảm ơn những người đã đồng hành cùng bạn trên hành trình.',
    'Hãy biến mỗi ngày làm việc thành một ngày ý nghĩa.',
    'Người dám ước mơ lớn sẽ có động lực để cố gắng nhiều hơn.',
    'Thành công không đến từ một sớm một chiều, mà từ sự tích lũy mỗi ngày.',
    'Hãy giữ cho mình một tinh thần cầu tiến trong mọi công việc.',
    'Sự chân thành trong công việc sẽ tạo dựng niềm tin lâu dài.',
    'Đừng để những điều nhỏ nhặt làm mất đi niềm vui lớn lao.',
    'Hãy làm việc với niềm đam mê, thành công sẽ theo sau.',
    'Người mạnh mẽ là người biết đứng dậy sau mỗi lần vấp ngã.',
    'Sự chăm chỉ hôm nay là nền tảng cho thành công ngày mai.',
    'Hãy trân trọng từng khoảnh khắc bên gia đình và đồng nghiệp.',
    'Đừng để sự trì hoãn cướp đi cơ hội của bạn.',
    'Một tinh thần tích cực có thể vượt qua mọi giới hạn.',
    'Hãy luôn giữ lửa nhiệt huyết trong công việc mỗi ngày.',
    'Người biết lập kế hoạch luôn đi trước một bước trong mọi việc.',
    'Sự đồng lòng của cả đội sẽ tạo nên sức mạnh không gì lay chuyển được.',
    'Hãy để mỗi thử thách là cơ hội để bạn chứng minh bản thân.',
    'Đừng ngừng cố gắng, vì thành công luôn dành cho người kiên trì.',
    'Một câu nói tử tế có thể sưởi ấm cả một ngày dài.',
    'Hãy sống trọn vẹn với hiện tại, vì đó là món quà quý giá nhất.',
    'Người có trách nhiệm luôn hoàn thành công việc dù khó khăn đến đâu.',
    'Sự sáng tạo bắt nguồn từ việc dám thử những điều mới mẻ.',
    'Hãy luôn nhớ rằng bạn không đơn độc trên hành trình này.',
    'Đừng để nỗi sợ thất bại ngăn cản bạn thử sức với điều mới.',
    'Một ngày làm việc hiệu quả bắt đầu từ một buổi sáng tích cực.',
    'Hãy biết trân trọng những gì mình đang có trước khi nó trở thành kỷ niệm.',
    'Người giữ được bình tĩnh trong khó khăn luôn tìm ra giải pháp tốt nhất.',
    'Sự cố gắng bền bỉ sẽ luôn được đền đáp xứng đáng.',
    'Hãy để lòng biết ơn dẫn lối cho mọi hành động của bạn.',
    'Đừng quên rằng mỗi thành công nhỏ đều đáng được ăn mừng.',
    'Một tập thể gắn kết sẽ vượt qua mọi thử thách dễ dàng hơn.',
    'Hãy luôn giữ nụ cười, vì đó là vũ khí mạnh nhất chống lại khó khăn.',
    'Người có tầm nhìn xa luôn chuẩn bị cho những điều chưa xảy ra.',
    'Sự chăm sóc khách hàng tận tâm là chìa khóa giữ chân họ lâu dài.',
    'Hãy làm việc với cả trái tim, không chỉ với đôi tay.',
    'Đừng để một ngày mệt mỏi làm bạn quên đi lý do mình bắt đầu.',
    'Một lời cảm ơn chân thành có giá trị hơn bất kỳ món quà nào.',
    'Hãy tin rằng những gì bạn gieo hôm nay sẽ nở hoa vào một ngày không xa.',
    'Người biết chia sẻ khó khăn luôn nhận được sự giúp đỡ khi cần.',
    'Sự kiên trì trong công việc nhỏ sẽ dẫn đến thành công lớn.',
    'Hãy để mỗi buổi sáng là một khởi đầu tràn đầy năng lượng.',
    'Đừng ngại thay đổi, vì đó là cách duy nhất để tiến bộ.',
    'Một đội ngũ đoàn kết có thể biến điều không thể thành có thể.',
    'Hãy luôn đặt chất lượng lên hàng đầu trong mọi công việc.',
    'Người dám nhận trách nhiệm luôn được tin tưởng giao phó nhiều hơn.',
    'Sự tận tụy trong công việc sẽ mang lại thành quả xứng đáng.',
    'Hãy nhớ rằng mỗi nụ cười bạn trao đi đều có giá trị riêng.',
    'Đừng để khó khăn hôm nay làm bạn quên đi ước mơ ngày mai.',
    'Một người lãnh đạo tốt luôn đồng hành cùng đội ngũ trong mọi hoàn cảnh.',
    'Hãy tin vào sức mạnh của sự kiên nhẫn và bền bỉ.',
    'Người biết lắng nghe khách hàng sẽ hiểu được điều họ thực sự cần.',
    'Sự tích cực trong suy nghĩ sẽ dẫn đến hành động tích cực.',
    'Hãy trân trọng mỗi cơ hội học hỏi trong công việc hàng ngày.',
    'Đừng để sự so sánh làm bạn quên đi giá trị của chính mình.',
    'Một môi trường làm việc tôn trọng lẫn nhau sẽ nuôi dưỡng sự sáng tạo.',
    'Hãy giữ vững niềm tin, vì mọi nỗ lực đều có ý nghĩa riêng.',
    'Người biết ơn công việc của mình sẽ luôn tìm thấy niềm vui trong đó.',
    'Sự chuẩn bị chu đáo là nửa chặng đường của thành công.',
    'Hãy để mỗi ngày trôi qua đều để lại điều gì đó ý nghĩa.',
    'Đừng quên rằng sức khỏe là tài sản quý giá nhất của mỗi người.',
    'Một lời động viên đúng lúc có thể tiếp thêm sức mạnh cho cả một ngày.',
    'Hãy sống với lòng biết ơn, vì đó là chìa khóa của hạnh phúc.',
    'Người kiên định với mục tiêu sẽ không dễ dàng bị lung lay.',
    'Sự đồng cảm giúp ta hiểu và gắn kết với người khác nhiều hơn.',
    'Hãy để mỗi thử thách trở thành cơ hội để bạn học hỏi và trưởng thành.',
    'Đừng ngại bắt đầu từ những bước nhỏ, vì hành trình vạn dặm bắt đầu từ một bước chân.',
    'Một tinh thần cầu tiến sẽ giúp bạn không ngừng phát triển bản thân.',
    'Hãy trân trọng những người luôn ở bên cạnh giúp đỡ bạn.',
    'Người biết quản lý thời gian tốt sẽ đạt được nhiều thành công hơn.',
    'Sự chân thành trong giao tiếp sẽ xây dựng những mối quan hệ bền vững.',
    'Hãy luôn giữ cho mình một trái tim rộng mở với mọi người xung quanh.',
    'Đừng để một lần thất bại làm bạn nghi ngờ khả năng của chính mình.',
    'Một ngày làm việc tận tâm sẽ mang lại một đêm ngủ ngon giấc.',
    'Hãy tin rằng mỗi nỗ lực nhỏ đều góp phần vào thành công lớn.',
    'Người có kỷ luật cao luôn đạt được mục tiêu đề ra.',
    'Sự linh hoạt trong công việc giúp ta thích nghi với mọi hoàn cảnh.',
    'Hãy để mỗi ngày mới là cơ hội để bạn trở thành phiên bản tốt hơn.',
    'Đừng để nỗi buồn hôm nay che mờ hy vọng ngày mai.',
    'Một tập thể biết sẻ chia sẽ luôn vững vàng trước mọi sóng gió.',
    'Hãy giữ vững niềm đam mê, vì đó là ngọn lửa nuôi dưỡng thành công.',
    'Người biết trân trọng thời gian sẽ không để nó trôi qua vô ích.',
    'Sự nhiệt tình trong công việc sẽ lan tỏa đến những người xung quanh.',
    'Hãy luôn nhớ rằng thành công là hành trình, không phải đích đến.',
    'Đừng quên chăm sóc tâm hồn mình giữa những bộn bề công việc.',
    'Một lời khen chân thành có thể tạo động lực cho cả một ngày dài.',
    'Hãy tin vào giá trị của sự cố gắng, dù kết quả chưa như mong đợi.',
    'Người biết ơn những gì mình có sẽ luôn cảm thấy đủ đầy.',
    'Sự kiên trì sẽ biến những điều tưởng chừng không thể thành có thể.',
    'Hãy để mỗi hành động nhỏ hôm nay tạo nên sự khác biệt lớn.',
    'Đừng để áp lực công việc làm bạn quên đi niềm vui trong cuộc sống.',
    'Một người đồng nghiệp tốt luôn sẵn sàng giúp đỡ khi cần thiết.',
    'Hãy giữ tinh thần lạc quan, vì đó là nguồn năng lượng vô tận.',
    'Người dám thay đổi sẽ luôn tìm thấy cơ hội mới cho bản thân.',
    'Sự tôn trọng thời gian của người khác cũng là tôn trọng chính mình.',
    'Hãy để công việc trở thành niềm vui, không phải gánh nặng.',
    'Đừng ngại nhận lỗi khi sai, vì đó là cách để trưởng thành hơn.',
    'Một tinh thần trách nhiệm cao sẽ tạo dựng niềm tin từ mọi người.',
    'Hãy luôn giữ cho mình sự khiêm tốn dù đạt được thành công lớn.',
    'Người biết cân bằng giữa công việc và cuộc sống sẽ hạnh phúc hơn.',
    'Sự chân thật luôn là nền tảng của mọi mối quan hệ bền vững.',
    'Hãy để mỗi ngày làm việc đều tràn đầy niềm vui và ý nghĩa.',
    'Đừng để những lời chỉ trích làm bạn quên đi giá trị của bản thân.',
    'Một tập thể vững mạnh được xây dựng từ sự tin tưởng lẫn nhau.',
    'Hãy tin rằng mọi khó khăn đều có cách giải quyết nếu ta kiên trì.',
    'Người biết lắng nghe sẽ học được nhiều điều quý giá từ người khác.',
    'Sự chăm chỉ và kiên nhẫn luôn mang lại kết quả xứng đáng.',
    'Hãy để lòng nhiệt huyết dẫn lối cho mọi công việc bạn làm.',
    'Đừng quên rằng mỗi ngày đều là cơ hội để bạn tỏa sáng.',
    'Một nụ cười thân thiện có thể xóa tan mọi khoảng cách.',
    'Hãy giữ vững niềm tin vào tương lai, dù hiện tại còn nhiều khó khăn.',
    'Người biết trân trọng công sức của người khác sẽ được tôn trọng lại.',
    'Sự cầu tiến giúp ta không ngừng hoàn thiện bản thân mỗi ngày.',
    'Hãy để mỗi trải nghiệm, dù tốt hay xấu, trở thành bài học quý giá.',
    'Đừng để sự mệt mỏi làm bạn quên đi mục tiêu ban đầu của mình.',
    'Một tinh thần đồng đội mạnh mẽ sẽ giúp vượt qua mọi trở ngại.',
    'Hãy luôn nhớ rằng bạn xứng đáng với những điều tốt đẹp trong cuộc sống.',
    'Người kiên định với giá trị của mình sẽ không dễ bị lay chuyển.',
    'Sự tận tâm trong từng việc nhỏ sẽ tạo nên sự khác biệt lớn.',
    'Hãy để mỗi ngày là một cơ hội để bạn học hỏi điều mới.',
    'Đừng ngại chia sẻ khó khăn với những người xung quanh bạn.',
    'Một môi trường làm việc tích cực sẽ nuôi dưỡng sự phát triển của mỗi người.',
    'Hãy giữ cho mình một tâm hồn rộng mở và biết ơn.',
    'Người dám đối mặt với thử thách sẽ trưởng thành nhanh hơn.',
    'Sự chân thành trong từng lời nói sẽ xây dựng niềm tin lâu dài.',
    'Hãy để mỗi khó khăn trở thành động lực để bạn cố gắng hơn.',
    'Đừng quên rằng thành công luôn đi kèm với sự kiên trì bền bỉ.',
    'Một lời cảm ơn đúng lúc có thể làm ấm lòng người nhận.',
    'Hãy tin rằng mỗi nỗ lực của bạn đều có giá trị riêng của nó.',
    'Người biết trân trọng hiện tại sẽ sống một cuộc đời ý nghĩa hơn.',
    'Sự đoàn kết trong công việc sẽ giúp mọi khó khăn trở nên dễ dàng hơn.',
    'Hãy để mỗi ngày làm việc là một hành trình đầy cảm hứng.',
    'Đừng để sự do dự làm bạn bỏ lỡ những cơ hội quý giá.',
    'Một tinh thần cầu thị sẽ giúp bạn học hỏi được nhiều điều mới.',
    'Hãy giữ vững sự lạc quan, vì đó là ánh sáng dẫn lối qua khó khăn.',
    'Người biết ơn cuộc sống sẽ luôn tìm thấy niềm vui trong công việc.',
    'Sự kiên nhẫn với bản thân cũng quan trọng như kiên nhẫn với người khác.',
    'Hãy để mỗi thành công nhỏ tiếp thêm động lực cho những mục tiêu lớn hơn.',
    'Đừng để một ngày khó khăn làm bạn quên đi những ngày tươi đẹp đã qua.',
    'Một tập thể biết tôn trọng sự khác biệt sẽ luôn sáng tạo và phát triển.',
    'Hãy tin vào chính mình, vì bạn mạnh mẽ hơn bạn nghĩ.',
    'Người biết chăm sóc bản thân sẽ có nhiều năng lượng để chăm sóc người khác.',
    'Sự tận tụy trong công việc sẽ được ghi nhận theo thời gian.',
    'Hãy để mỗi ngày mới mang đến cho bạn nguồn cảm hứng mới.',
    'Đừng ngại thử sức với những điều nằm ngoài vùng an toàn của bạn.',
    'Một tinh thần trách nhiệm cao sẽ giúp bạn hoàn thành mọi việc tốt đẹp.',
    'Hãy luôn nhớ rằng sự cố gắng hôm nay là nền tảng cho ngày mai tươi sáng.',
    'Người biết trân trọng từng phút giây sẽ không bao giờ cảm thấy lãng phí thời gian.',
    'Hãy để sự chăm chỉ trở thành thói quen, không phải gánh nặng.',
    'Đừng để một lời từ chối làm bạn nản lòng trước những cơ hội khác.',
    'Một tinh thần cầu tiến sẽ đưa bạn đi xa hơn bạn tưởng.',
    'Hãy giữ cho mình sự bình an trong tâm hồn giữa những bộn bề cuộc sống.',
    'Người biết ơn sẽ luôn thấy cuộc sống này thật đáng sống.',
    'Sự chân thành và nỗ lực luôn được đền đáp xứng đáng theo thời gian.',
    'Hãy để mỗi ngày trôi qua đều mang lại cho bạn một điều học hỏi mới.',
    'Đừng ngại thất bại, vì đó là bước đệm để tiến gần hơn đến thành công.',
    'Một người có tâm luôn được đồng nghiệp và khách hàng tin yêu.',
    'Hãy giữ vững tinh thần lạc quan, dù con đường phía trước còn nhiều thử thách.',
    'Người biết sẻ chia niềm vui sẽ nhân đôi hạnh phúc của mình.',
    'Sự kiên trì không ngừng nghỉ sẽ giúp bạn chạm đến ước mơ.',
    'Hãy để mỗi nụ cười của bạn trở thành nguồn động lực cho người khác.',
    'Đừng để những khó khăn nhỏ làm bạn quên đi bức tranh lớn của cuộc đời.',
    'Một tập thể gắn bó sẽ cùng nhau vượt qua mọi giông bão.',
    'Hãy tin rằng những gì tốt đẹp đang chờ đợi bạn ở phía trước.',
    'Người biết dừng lại đúng lúc để nghỉ ngơi sẽ đi được xa hơn.',
    'Sự tôn trọng lẫn nhau là nền tảng của mọi mối quan hệ bền chặt.',
    'Hãy để công việc hôm nay là bước đệm vững chắc cho thành công ngày mai.',
    'Đừng quên rằng mỗi người xung quanh bạn đều đang cố gắng hết mình.',
    'Một trái tim ấm áp sẽ luôn tìm được chỗ đứng trong lòng người khác.',
    'Hãy giữ cho mình niềm tin rằng mọi nỗ lực đều không vô ích.',
    'Người biết yêu thương công việc của mình sẽ luôn làm việc với niềm vui.',
    'Sự bền bỉ theo thời gian sẽ biến những giấc mơ nhỏ thành hiện thực lớn.',
  ],

  BUDDHIST_QUOTES: [
    'Tâm an thì vạn sự an, tâm loạn thì vạn sự loạn.',
    'Buông bỏ không phải là từ bỏ, mà là không còn nắm giữ những gì làm ta khổ.',
    'Hạnh phúc không đến từ việc có nhiều, mà đến từ việc muốn ít.',
    'Mọi khổ đau đều bắt nguồn từ sự chấp trước, buông được là nhẹ được.',
    'Sống trong hiện tại, đừng để quá khứ dày vò, đừng để tương lai lo âu.',
    'Từ bi với người khác chính là từ bi với chính mình.',
    'Gieo nhân nào gặt quả nấy, gieo thiện lành sẽ gặt an vui.',
    'Tha thứ cho người là cởi trói cho chính mình.',
    'Vô thường là quy luật của cuộc sống, đón nhận nó bằng tâm bình thản.',
    'Người tu tâm không cần ở chùa, chỉ cần giữ tâm thanh tịnh giữa đời thường.',
    'Sân hận như lửa đốt cháy chính người đang giữ nó trong lòng.',
    'Nụ cười an nhiên là biểu hiện của một tâm hồn đã buông bỏ được nhiều điều.',
    'Đừng tìm hạnh phúc ở nơi xa, hạnh phúc nằm ngay trong tâm mình.',
    'Tham lam là gốc rễ của mọi khổ đau, biết đủ là gốc rễ của an vui.',
    'Người có trí tuệ nhìn thấu vô thường sẽ không còn sợ hãi mất mát.',
    'Một tâm tĩnh lặng có thể nhìn rõ vạn vật như chúng vốn là.',
    'Từng hơi thở là một cơ hội để trở về với hiện tại.',
    'Oán hận không giải quyết được gì, chỉ có yêu thương mới hóa giải được hận thù.',
    'Người biết đủ là người giàu có nhất, dù không có nhiều của cải.',
    'Cơn giận là con dao hai lưỡi, làm tổn thương người khác trước khi làm tổn thương chính mình.',
    'Học cách im lặng đúng lúc cũng là một loại trí tuệ.',
    'Chấp niệm càng nhiều, khổ đau càng lớn.',
    'Sống chậm lại để lắng nghe tiếng nói bên trong tâm hồn mình.',
    'Mọi thứ đến rồi đi, chỉ có tâm an lạc là điều ta có thể giữ mãi.',
    'Người tu hành thật sự là người biết kiểm soát tâm mình trong từng khoảnh khắc.',
    'Đừng phán xét người khác khi ta chưa hiểu hết hoàn cảnh của họ.',
    'Từ bi và trí tuệ là hai đôi cánh giúp tâm hồn bay xa khỏi khổ đau.',
    'Cuộc sống là một dòng chảy, cưỡng lại chỉ khiến ta thêm mệt mỏi.',
    'Học cách buông tay đúng lúc cũng là một nghệ thuật sống.',
    'Người an nhiên là người không còn để ngoại cảnh làm xáo trộn nội tâm.',
    'Tâm từ bi rộng mở sẽ không còn chỗ cho oán hờn tồn tại.',
    'Khổ đau là thầy dạy cho ta những bài học quý giá nhất trong đời.',
    'Đừng để những chuyện nhỏ nhặt làm vẩn đục tâm hồn thanh tịnh.',
    'Sự tĩnh lặng bên trong mạnh mẽ hơn mọi giông bão bên ngoài.',
    'Người biết ơn cuộc đời sẽ luôn thấy đủ đầy trong mọi hoàn cảnh.',
    'Hãy để lòng từ bi dẫn dắt mọi hành động và lời nói của mình.',
    'Mỗi ngày sống trọn vẹn là một ngày tu tập chân chính.',
    'Buông bỏ không có nghĩa là mất đi, mà là để tâm được nhẹ nhàng hơn.',
    'Người có tâm rộng lượng sẽ không bị giam cầm bởi những điều nhỏ nhặt.',
    'Cuộc đời như giấc mộng, tỉnh giấc rồi mới biết mọi thứ đều vô thường.',
    'Hãy gieo hạt giống thiện lành, dù nhỏ bé, để mai này gặt được quả ngọt.',
    'Tâm bình an là tài sản quý giá nhất mà không ai có thể lấy đi được.',
    'Người trí tuệ biết khi nào nên nói, khi nào nên im lặng.',
    'Đừng để quá khứ trở thành gánh nặng cho hiện tại.',
    'Học cách yêu thương bản thân trước khi học cách yêu thương người khác.',
    'Sự giận dữ chỉ tồn tại trong khoảnh khắc, nhưng hậu quả có thể kéo dài.',
    'Người hiểu được lẽ vô thường sẽ sống trọn vẹn hơn từng khoảnh khắc.',
    'Từ bi không phải là yếu đuối, mà là sức mạnh của một tâm hồn lớn.',
    'Hãy để mỗi việc làm đều xuất phát từ lòng chân thành.',
    'Người tu tâm là người biết chuyển hóa khổ đau thành bài học trưởng thành.',
    'Cuộc sống an lạc bắt đầu từ một tâm hồn không còn oán trách.',
    'Đừng tìm kiếm sự hoàn hảo bên ngoài, hãy tìm sự bình an bên trong.',
    'Người biết buông bỏ quá khứ sẽ có nhiều không gian hơn cho hiện tại.',
    'Từng suy nghĩ thiện lành đều gieo mầm cho một cuộc sống tốt đẹp hơn.',
    'Hạnh phúc chân thật không phụ thuộc vào những gì ta sở hữu.',
    'Người có tâm từ bi sẽ luôn tìm thấy lý do để tha thứ.',
    'Đời người ngắn ngủi, đừng lãng phí vào những oán hận không đáng có.',
    'Sự tĩnh tâm giúp ta nhìn rõ bản chất của mọi vấn đề.',
    'Hãy sống như đóa sen, vươn lên từ bùn lầy nhưng vẫn giữ được sự thanh khiết.',
    'Người biết ơn sẽ không bao giờ cảm thấy thiếu thốn.',
    'Buông bỏ chấp niệm là bước đầu tiên trên con đường an lạc.',
    'Tâm từ bi không phân biệt, luôn rộng mở với mọi chúng sinh.',
    'Mỗi khoảnh khắc hiện tại đều là món quà quý giá nếu ta biết trân trọng.',
    'Người tu tâm không tránh né khó khăn, mà học cách đối diện với chúng bằng sự bình thản.',
    'Nội tâm an định thì ngoại cảnh dù biến động cũng không làm ta lay chuyển.',
    'Hãy để lòng bao dung xóa tan mọi hiềm khích trong tâm.',
    'Sự khiêm nhường là biểu hiện của một tâm hồn đã thấu hiểu lẽ vô ngã.',
    'Người sống thiện lành sẽ luôn cảm nhận được sự bình yên trong tâm.',
    'Đừng để những lời khen chê làm lay động tâm hồn vốn dĩ an tĩnh.',
    'Từ bi hỷ xả là con đường dẫn đến một tâm hồn tự do.',
    'Người hiểu rõ nhân quả sẽ cẩn trọng trong từng lời nói và hành động.',
    'Hãy để mỗi ngày trôi qua đều là một ngày ta sống tỉnh thức hơn.',
    'Buông bỏ oán hận là món quà lớn nhất ta có thể tặng cho chính mình.',
    'Người có tâm tĩnh lặng sẽ không dễ dàng bị cuốn theo cảm xúc nhất thời.',
    'Cuộc sống là chuỗi những thay đổi, chấp nhận nó là cách để sống an nhiên.',
    'Hãy gieo yêu thương ở mọi nơi mình đi qua, dù chỉ bằng một nụ cười.',
    'Người có trí tuệ biết rằng mọi phiền não đều xuất phát từ chính tâm mình.',
    'Tâm thanh tịnh như mặt hồ phẳng lặng, phản chiếu mọi thứ một cách rõ ràng.',
    'Đừng để tham vọng che mờ đi giá trị thật sự của cuộc sống.',
    'Hãy học cách tha thứ, không phải vì người khác xứng đáng, mà vì tâm mình xứng đáng được nhẹ nhàng.',
    'Người an nhiên không phải là người không gặp khó khăn, mà là người vượt qua nó với tâm bình thản.',
    'Từng bước chân chánh niệm đưa ta gần hơn với sự tự do nội tâm.',
    'Hạnh phúc không nằm ở đích đến, mà nằm trong từng bước ta đi.',
    'Người biết đủ sẽ không bị cuốn theo vòng xoáy của tham cầu vô tận.',
    'Hãy để tâm từ bi lan tỏa như ánh sáng, soi rọi cả những nơi tối tăm nhất.',
    'Sự bình yên thật sự đến từ việc chấp nhận mọi thứ như chúng vốn là.',
    'Người tu tâm không mong cầu điều hoàn hảo, mà học cách an trú trong sự bất toàn.',
    'Đừng để cái tôi che lấp đi sự thật, hãy sống với sự khiêm nhường chân thật.',
    'Từng lời nói ái ngữ có thể xoa dịu cả một tâm hồn đang tổn thương.',
    'Hãy nhìn mọi khó khăn như một cơ hội để tâm ta trưởng thành hơn.',
    'Người có lòng từ bi sẽ không bao giờ thấy cô đơn, vì họ luôn kết nối với mọi chúng sinh.',
    'Sự tĩnh lặng của tâm hồn là nơi trú ẩn an toàn nhất giữa cuộc đời nhiều biến động.',
    'Đừng chạy theo những gì phù du, hãy tìm kiếm những giá trị bền vững trong tâm.',
    'Người hiểu lẽ vô thường sẽ trân trọng hơn từng khoảnh khắc bên người thân yêu.',
    'Hãy để mỗi hành động đều xuất phát từ tâm từ bi, không mong cầu đền đáp.',
    'Buông bỏ không phải là yếu đuối, mà là biểu hiện của một tâm hồn mạnh mẽ và tự do.',
    'Người sống chánh niệm sẽ tìm thấy sự bình an ngay trong những công việc thường ngày.',
    'Từ bi với chính mình cũng quan trọng như từ bi với người khác.',
    'Hãy để sự biết ơn trở thành thói quen mỗi ngày, dù trong hoàn cảnh nào.',
    'Người có tâm rộng mở sẽ không bị giới hạn bởi những định kiến hẹp hòi.',
    'Đau khổ đến từ sự cưỡng cầu, an lạc đến từ sự chấp nhận.',
    'Hãy sống như dòng nước, mềm mại nhưng có thể vượt qua mọi trở ngại.',
    'Người tu tâm hiểu rằng hạnh phúc và khổ đau đều là những vị khách tạm thời.',
    'Từng khoảnh khắc tỉnh thức là một bước tiến trên con đường giác ngộ.',
    'Hãy để lòng bao dung xóa nhòa những ranh giới của sự phân biệt.',
    'Người biết buông bỏ sẽ tìm thấy tự do ngay trong chính cuộc sống này.',
    'Sự giận dữ giống như nắm than hồng, người ném nó ra trước tiên tự làm bỏng tay mình.',
    'Hãy tu tâm dưỡng tính mỗi ngày, như tưới nước cho một khu vườn an lạc.',
    'Người sống với tâm từ bi sẽ gặt hái được sự bình yên trong tâm hồn.',
    'Đừng để những mong cầu vô tận cướp đi niềm vui của hiện tại.',
    'Hãy học cách lắng nghe tâm mình trước khi phản ứng với ngoại cảnh.',
    'Người có trí tuệ hiểu rằng mọi vật đều biến đổi, không có gì là mãi mãi.',
    'Từ bi là ngọn đèn soi sáng con đường của những tâm hồn lạc lối.',
    'Hãy sống với lòng chân thành, đó là nền tảng của mọi mối quan hệ tốt đẹp.',
    'Người an lạc là người đã học được cách sống hòa hợp với chính mình.',
    'Đừng tìm kiếm sự công nhận từ bên ngoài, hãy tìm sự bình an từ bên trong.',
    'Hãy để mỗi hơi thở nhắc nhở ta về sự quý giá của khoảnh khắc hiện tại.',
    'Người có tâm từ bi sẽ luôn nhìn thấy điều tốt đẹp trong mỗi con người.',
    'Sự tha thứ không làm thay đổi quá khứ, nhưng làm rộng mở tương lai.',
    'Hãy tu dưỡng tâm hồn như người làm vườn chăm sóc từng gốc cây nhỏ.',
    'Người hiểu lẽ nhân quả sẽ sống thận trọng và từ bi hơn mỗi ngày.',
    'Đừng để nỗi sợ hãi kiểm soát tâm trí, hãy để trí tuệ dẫn đường.',
    'Hãy sống với tâm rộng mở, đón nhận mọi trải nghiệm như những bài học quý giá.',
    'Người có tâm bình thản sẽ không bị lay động bởi những lời khen chê của thế gian.',
    'Từ bi và trí tuệ song hành sẽ dẫn dắt ta đến một cuộc sống an lạc.',
    'Hãy để mỗi ngày là một cơ hội để buông bỏ thêm một chút chấp niệm.',
    'Người sống tỉnh thức sẽ nhận ra hạnh phúc luôn hiện diện trong những điều giản dị.',
    'Đừng để quá khứ hay tương lai cướp đi sự bình an của hiện tại.',
    'Hãy học cách yêu thương vô điều kiện, như ánh mặt trời chiếu sáng khắp muôn nơi.',
    'Người có tâm từ bi sẽ không bao giờ để hận thù ngự trị trong lòng.',
    'Sự khiêm tốn giúp ta học hỏi được nhiều điều từ cuộc sống xung quanh.',
    'Hãy để tâm hồn nhẹ nhàng như mây trôi, không vướng bận điều gì.',
    'Người tu tâm hiểu rằng mọi khổ đau đều có thể chuyển hóa thành trí tuệ.',
    'Đừng để cái tôi lớn lao che khuất đi sự khiêm nhường cần thiết.',
    'Hãy sống với lòng biết ơn, vì mỗi khoảnh khắc đều là một món quà.',
    'Người có trí tuệ sẽ không phán xét người khác qua vẻ bề ngoài.',
    'Từ bi là chìa khóa mở ra cánh cửa của một trái tim rộng lớn.',
    'Hãy để sự tĩnh lặng trong tâm dẫn dắt mọi quyết định của cuộc đời.',
    'Người an nhiên trước sóng gió là người đã tìm thấy sự vững chãi bên trong.',
    'Đừng để những ham muốn nhỏ nhặt làm lu mờ đi mục đích sống lớn lao.',
    'Hãy tu tâm mỗi ngày, như mài giũa một viên ngọc cho đến khi nó tỏa sáng.',
    'Người sống với chánh niệm sẽ không bị cuốn theo những vọng tưởng của tâm trí.',
    'Từ bi không có biên giới, nó vượt qua mọi khác biệt giữa con người.',
    'Hãy để mỗi lời nói đều mang theo sự chân thành và yêu thương.',
    'Người hiểu được vô thường sẽ không còn sợ hãi trước sự đổi thay.',
    'Đừng để những phiền não nhỏ nhặt làm mất đi sự bình an lớn lao.',
    'Hãy sống như đóa hoa, tỏa hương thơm mà không cần ai công nhận.',
    'Người có tâm từ bi sẽ luôn tìm cách giúp đỡ người khác mà không mong đền đáp.',
    'Sự tĩnh tâm là nền tảng để ta đưa ra những quyết định sáng suốt.',
    'Hãy để lòng bao dung trở thành người bạn đồng hành trong mọi hoàn cảnh.',
    'Người biết buông bỏ sẽ tìm thấy sự nhẹ nhàng trong từng bước đi.',
    'Đừng để nỗi lo âu về tương lai làm mất đi niềm vui của hiện tại.',
    'Hãy tu dưỡng tâm từ bi như tưới tắm cho một khu vườn tâm hồn.',
    'Người sống chân thành sẽ luôn nhận được sự tin yêu từ những người xung quanh.',
    'Từ bi giúp ta nhìn thấy nỗi khổ của người khác như nỗi khổ của chính mình.',
    'Hãy để mỗi ngày sống đều là một cơ hội để thực hành lòng từ bi.',
    'Người có tâm an định sẽ không dễ bị dao động bởi những biến cố bên ngoài.',
    'Đừng để sự sân hận làm mờ đi ánh sáng trí tuệ trong tâm.',
    'Hãy sống với sự khiêm nhường, vì không ai là hoàn hảo cả.',
    'Người hiểu lẽ vô ngã sẽ không còn bám chấp vào cái tôi nhỏ bé.',
    'Từ bi là con đường ngắn nhất dẫn đến sự an lạc của tâm hồn.',
    'Hãy để tâm hồn được nghỉ ngơi trong sự tĩnh lặng của hiện tại.',
    'Người sống với lòng biết ơn sẽ luôn tìm thấy niềm vui trong những điều nhỏ bé.',
    'Đừng để những mong cầu vô tận trở thành gánh nặng cho tâm hồn.',
    'Hãy học cách chấp nhận những gì không thể thay đổi, và thay đổi những gì có thể.',
    'Người có tâm từ bi sẽ luôn đối xử với muôn loài bằng sự tôn trọng.',
    'Sự bình an không đến từ việc không có vấn đề, mà đến từ việc biết cách đối diện với chúng.',
    'Hãy để mỗi ngày trôi qua đều để lại dấu ấn của sự tử tế.',
    'Người tu tâm hiểu rằng mọi hành động đều gieo hạt giống cho tương lai.',
    'Đừng để những tổn thương trong quá khứ định hình con người bạn hôm nay.',
    'Hãy sống với sự rộng lượng, vì cho đi cũng là một cách nhận lại.',
    'Người có trí tuệ sẽ biết phân biệt giữa điều thật sự quan trọng và điều phù du.',
    'Từ bi giúp ta kết nối với mọi chúng sinh bằng một trái tim rộng mở.',
    'Hãy để sự tĩnh lặng trong tâm trở thành nơi ta luôn có thể quay về.',
    'Người sống tỉnh thức sẽ nhận ra giá trị của mỗi hơi thở trong cuộc sống.',
    'Đừng để cái tôi ngăn cản ta học hỏi từ những người xung quanh.',
    'Hãy tu dưỡng lòng từ bi như một thói quen hàng ngày, không cần lý do đặc biệt.',
    'Người có tâm an lạc sẽ lan tỏa sự bình yên đến những người xung quanh.',
    'Sự khiêm tốn là dấu hiệu của một tâm hồn đã hiểu được sự vô hạn của tri thức.',
    'Hãy để mỗi khó khăn trở thành cơ hội để ta thực hành sự kiên nhẫn.',
    'Người sống với lòng từ bi sẽ không bao giờ cảm thấy cô đơn trong cuộc đời.',
    'Đừng để những phán xét vội vàng làm tổn thương mối quan hệ với người khác.',
    'Hãy học cách tha thứ cho chính mình trước khi mong người khác tha thứ.',
    'Người có tâm rộng mở sẽ đón nhận mọi trải nghiệm như một phần của hành trình.',
    'Từ bi không phải là sự thương hại, mà là sự thấu hiểu sâu sắc.',
    'Hãy để mỗi ngày sống đều là một bước tiến trên con đường tu tâm.',
    'Người hiểu lẽ nhân quả sẽ gieo trồng những hạt giống thiện lành mỗi ngày.',
    'Đừng để sự vội vã cuốn ta đi khỏi những giá trị thật sự của cuộc sống.',
    'Hãy sống với sự an nhiên, đón nhận mọi thứ đến và đi như dòng nước chảy.',
    'Người có tâm từ bi sẽ luôn tìm thấy cách để làm dịu nỗi đau của người khác.',
    'Sự tĩnh lặng bên trong giúp ta nhìn thấu bản chất thật của mọi sự việc.',
    'Hãy để lòng biết ơn dẫn dắt ta qua mọi thử thách của cuộc đời.',
    'Người sống chánh niệm sẽ không để tâm trí lang thang vào quá khứ hay tương lai.',
    'Đừng để những ham muốn vật chất làm lu mờ đi giá trị tinh thần.',
    'Hãy tu dưỡng tâm hồn như chăm sóc một khu vườn, cần thời gian và kiên nhẫn.',
    'Người có trí tuệ sẽ biết rằng hạnh phúc thật sự đến từ bên trong, không phải bên ngoài.',
    'Từ bi là ánh sáng giúp xua tan bóng tối của hận thù và oán trách.',
    'Hãy để mỗi bước chân đều mang theo sự tỉnh thức và chánh niệm.',
    'Người sống với lòng từ bi sẽ luôn tìm thấy bình an dù ở bất cứ đâu.',
    'Đừng để sự kiêu ngạo che mờ đi sự thật về bản chất vô thường của mọi vật.',
    'Hãy học cách yêu thương mà không mong cầu được yêu thương lại.',
    'Người có tâm an định sẽ đối diện với khó khăn bằng sự bình thản và trí tuệ.',
    'Sự từ bi chân thật không phân biệt giàu nghèo, sang hèn.',
    'Hãy để mỗi ngày sống đều là cơ hội để gieo trồng thêm hạt giống yêu thương.',
    'Người biết trân trọng thời gian sẽ không để nó trôi qua vô ích.',
    'Sự nhiệt tình trong công việc sẽ lan tỏa đến những người xung quanh.',
    'Hãy luôn nhớ rằng thành công là hành trình, không phải đích đến.',
    'Đừng quên chăm sóc tâm hồn mình giữa những bộn bề công việc.',
    'Một lời khen chân thành có thể tạo động lực cho cả một ngày dài.',
    'Hãy tin vào giá trị của sự cố gắng, dù kết quả chưa như mong đợi.',
    'Người biết ơn những gì mình có sẽ luôn cảm thấy đủ đầy.',
    'Sự kiên trì sẽ biến những điều tưởng chừng không thể thành có thể.',
    'Hãy để mỗi hành động nhỏ hôm nay tạo nên sự khác biệt lớn.',
    'Đừng để áp lực công việc làm bạn quên đi niềm vui trong cuộc sống.',
    'Một người đồng nghiệp tốt luôn sẵn sàng giúp đỡ khi cần thiết.',
    'Hãy giữ tinh thần lạc quan, vì đó là nguồn năng lượng vô tận.',
    'Người dám thay đổi sẽ luôn tìm thấy cơ hội mới cho bản thân.',
    'Sự tôn trọng thời gian của người khác cũng là tôn trọng chính mình.',
    'Hãy để công việc trở thành niềm vui, không phải gánh nặng.',
    'Đừng ngại nhận lỗi khi sai, vì đó là cách để trưởng thành hơn.',
    'Một tinh thần trách nhiệm cao sẽ tạo dựng niềm tin từ mọi người.',
    'Hãy luôn giữ cho mình sự khiêm tốn dù đạt được thành công lớn.',
    'Người biết cân bằng giữa công việc và cuộc sống sẽ hạnh phúc hơn.',
    'Sự chân thật luôn là nền tảng của mọi mối quan hệ bền vững.',
    'Hãy để mỗi ngày làm việc đều tràn đầy niềm vui và ý nghĩa.',
    'Đừng để những lời chỉ trích làm bạn quên đi giá trị của bản thân.',
    'Một tập thể vững mạnh được xây dựng từ sự tin tưởng lẫn nhau.',
    'Hãy tin rằng mọi khó khăn đều có cách giải quyết nếu ta kiên trì.',
    'Người biết lắng nghe sẽ học được nhiều điều quý giá từ người khác.',
    'Sự chăm chỉ và kiên nhẫn luôn mang lại kết quả xứng đáng.',
    'Hãy để lòng nhiệt huyết dẫn lối cho mọi công việc bạn làm.',
    'Đừng quên rằng mỗi ngày đều là cơ hội để bạn tỏa sáng.',
    'Một nụ cười thân thiện có thể xóa tan mọi khoảng cách.',
    'Hãy giữ vững niềm tin vào tương lai, dù hiện tại còn nhiều khó khăn.',
    'Người biết trân trọng công sức của người khác sẽ được tôn trọng lại.',
    'Sự cầu tiến giúp ta không ngừng hoàn thiện bản thân mỗi ngày.',
    'Hãy để mỗi trải nghiệm, dù tốt hay xấu, trở thành bài học quý giá.',
    'Đừng để sự mệt mỏi làm bạn quên đi mục tiêu ban đầu của mình.',
    'Một tinh thần đồng đội mạnh mẽ sẽ giúp vượt qua mọi trở ngại.',
    'Hãy luôn nhớ rằng bạn xứng đáng với những điều tốt đẹp trong cuộc sống.',
    'Người kiên định với giá trị của mình sẽ không dễ bị lay chuyển.',
    'Sự tận tâm trong từng việc nhỏ sẽ tạo nên sự khác biệt lớn.',
    'Hãy để mỗi ngày là một cơ hội để bạn học hỏi điều mới.',
    'Đừng ngại chia sẻ khó khăn với những người xung quanh bạn.',
    'Một môi trường làm việc tích cực sẽ nuôi dưỡng sự phát triển của mỗi người.',
    'Hãy giữ cho mình một tâm hồn rộng mở và biết ơn.',
    'Người dám đối mặt với thử thách sẽ trưởng thành nhanh hơn.',
    'Sự chân thành trong từng lời nói sẽ xây dựng niềm tin lâu dài.',
    'Hãy để mỗi khó khăn trở thành động lực để bạn cố gắng hơn.',
    'Đừng quên rằng thành công luôn đi kèm với sự kiên trì bền bỉ.',
    'Một lời cảm ơn đúng lúc có thể làm ấm lòng người nhận.',
    'Hãy tin rằng mỗi nỗ lực của bạn đều có giá trị riêng của nó.',
    'Người biết trân trọng hiện tại sẽ sống một cuộc đời ý nghĩa hơn.',
    'Sự đoàn kết trong công việc sẽ giúp mọi khó khăn trở nên dễ dàng hơn.',
    'Hãy để mỗi ngày làm việc là một hành trình đầy cảm hứng.',
    'Đừng để sự do dự làm bạn bỏ lỡ những cơ hội quý giá.',
    'Một tinh thần cầu thị sẽ giúp bạn học hỏi được nhiều điều mới.',
    'Hãy giữ vững sự lạc quan, vì đó là ánh sáng dẫn lối qua khó khăn.',
    'Người biết ơn cuộc sống sẽ luôn tìm thấy niềm vui trong công việc.',
    'Sự kiên nhẫn với bản thân cũng quan trọng như kiên nhẫn với người khác.',
    'Hãy để mỗi thành công nhỏ tiếp thêm động lực cho những mục tiêu lớn hơn.',
    'Đừng để một ngày khó khăn làm bạn quên đi những ngày tươi đẹp đã qua.',
    'Một tập thể biết tôn trọng sự khác biệt sẽ luôn sáng tạo và phát triển.',
    'Hãy tin vào chính mình, vì bạn mạnh mẽ hơn bạn nghĩ.',
    'Người biết chăm sóc bản thân sẽ có nhiều năng lượng để chăm sóc người khác.',
    'Sự tận tụy trong công việc sẽ được ghi nhận theo thời gian.',
    'Hãy để mỗi ngày mới mang đến cho bạn nguồn cảm hứng mới.',
    'Đừng ngại thử sức với những điều nằm ngoài vùng an toàn của bạn.',
    'Một tinh thần trách nhiệm cao sẽ giúp bạn hoàn thành mọi việc tốt đẹp.',
    'Hãy luôn nhớ rằng sự cố gắng hôm nay là nền tảng cho ngày mai tươi sáng.',
    'Người biết trân trọng từng phút giây sẽ không bao giờ cảm thấy lãng phí thời gian.',
    'Hãy để sự chăm chỉ trở thành thói quen, không phải gánh nặng.',
    'Đừng để một lời từ chối làm bạn nản lòng trước những cơ hội khác.',
    'Một tinh thần cầu tiến sẽ đưa bạn đi xa hơn bạn tưởng.',
    'Hãy giữ cho mình sự bình an trong tâm hồn giữa những bộn bề cuộc sống.',
    'Người biết ơn sẽ luôn thấy cuộc sống này thật đáng sống.',
    'Sự chân thành và nỗ lực luôn được đền đáp xứng đáng theo thời gian.',
    'Hãy để mỗi ngày trôi qua đều mang lại cho bạn một điều học hỏi mới.',
    'Đừng ngại thất bại, vì đó là bước đệm để tiến gần hơn đến thành công.',
    'Một người có tâm luôn được đồng nghiệp và khách hàng tin yêu.',
    'Hãy giữ vững tinh thần lạc quan, dù con đường phía trước còn nhiều thử thách.',
    'Người biết sẻ chia niềm vui sẽ nhân đôi hạnh phúc của mình.',
    'Sự kiên trì không ngừng nghỉ sẽ giúp bạn chạm đến ước mơ.',
    'Hãy để mỗi nụ cười của bạn trở thành nguồn động lực cho người khác.',
    'Đừng để những khó khăn nhỏ làm bạn quên đi bức tranh lớn của cuộc đời.',
    'Một tập thể gắn bó sẽ cùng nhau vượt qua mọi giông bão.',
    'Hãy tin rằng những gì tốt đẹp đang chờ đợi bạn ở phía trước.',
    'Người biết dừng lại đúng lúc để nghỉ ngơi sẽ đi được xa hơn.',
    'Sự tôn trọng lẫn nhau là nền tảng của mọi mối quan hệ bền chặt.',
    'Hãy để công việc hôm nay là bước đệm vững chắc cho thành công ngày mai.',
    'Đừng quên rằng mỗi người xung quanh bạn đều đang cố gắng hết mình.',
    'Một trái tim ấm áp sẽ luôn tìm được chỗ đứng trong lòng người khác.',
    'Hãy giữ cho mình niềm tin rằng mọi nỗ lực đều không vô ích.',
    'Người biết yêu thương công việc của mình sẽ luôn làm việc với niềm vui.',
    'Sự bền bỉ theo thời gian sẽ biến những giấc mơ nhỏ thành hiện thực lớn.',
    'Người có tâm rộng mở sẽ tìm thấy an lạc ngay giữa những nghịch cảnh của cuộc đời.',
    'Đừng để những oán trách quá khứ ngăn cản ta xây dựng một tương lai tốt đẹp hơn.',
    'Hãy sống như hoa sen, không nhiễm bùn nhơ dù mọc lên từ bùn lầy.',
    'Người hiểu lẽ nhân quả sẽ không oán trách số phận mà tự soi lại chính mình.',
    'Từ bi là ngôn ngữ chung mà mọi trái tim đều có thể hiểu được.',
    'Hãy để mỗi lần vấp ngã trở thành cơ hội để tâm ta thêm vững vàng.',
    'Người sống với lòng biết ơn sẽ nhìn thấy phép màu trong những điều bình dị nhất.',
    'Đừng để sự sân hận nhất thời phá hủy công đức tu tập của nhiều năm.',
    'Hãy tu dưỡng tâm hồn bằng sự tỉnh thức trong từng suy nghĩ, lời nói, việc làm.',
    'Người có trí tuệ sẽ biết buông bỏ đúng lúc, đúng việc, đúng người.',
    'Sự an lạc không phải là đích đến, mà là cách ta bước đi trên con đường đời.',
    'Hãy để lòng từ bi soi sáng cả những góc khuất tăm tối nhất trong tâm hồn.',
    'Người sống chánh niệm sẽ nhận ra rằng mỗi hơi thở đều là một phép màu.',
    'Đừng để sự ganh ghét làm mờ đi ánh sáng thiện lành vốn có trong tâm.',
    'Hãy học cách tĩnh tâm giữa những xáo động của cuộc sống thường nhật.',
    'Người có tâm từ bi sẽ không bao giờ khép lại cánh cửa của lòng vị tha.',
    'Từ bi và trí tuệ là hai ngọn đèn soi sáng con đường tu tập của mỗi người.',
    'Hãy để mỗi ngày sống đều được nuôi dưỡng bằng sự tỉnh thức và yêu thương.',
    'Người hiểu lẽ vô thường sẽ không còn níu kéo những gì đã qua.',
    'Đừng để tâm trí bị cuốn vào vòng xoáy của những so sánh vô nghĩa.',
    'Hãy sống với sự giản dị, vì hạnh phúc thường ẩn mình trong những điều đơn sơ.',
    'Người có lòng từ bi sẽ cảm nhận được nỗi đau của người khác như của chính mình.',
    'Sự tĩnh lặng nội tâm là gốc rễ để mọi hành động trở nên sáng suốt.',
    'Hãy để lòng bao dung giúp ta vượt qua những hiểu lầm trong cuộc sống.',
    'Người sống tỉnh thức sẽ biết trân trọng những gì mình đang có ngay lúc này.',
    'Đừng để những dục vọng không có điểm dừng cuốn ta đi xa khỏi bình an.',
    'Hãy tu tâm bằng cách gieo trồng những suy nghĩ thiện lành mỗi ngày.',
    'Người có trí tuệ sẽ nhận ra rằng mọi cuộc gặp gỡ đều là duyên phận quý giá.',
    'Từ bi giúp ta buông bỏ sự phán xét để đón nhận sự thấu hiểu.',
    'Hãy để mỗi khó khăn trong đời trở thành bậc thang đưa tâm hồn ta đi lên.',
    'Người sống với sự an nhiên sẽ không còn sợ hãi trước những biến cố bất ngờ.',
    'Đừng để sự kiêu mạn ngăn cản ta cúi đầu học hỏi từ những điều giản đơn.',
    'Hãy học cách yêu thương mà không chiếm hữu, quan tâm mà không ràng buộc.',
    'Người có tâm từ bi sẽ gieo trồng hạt giống an lạc ở mọi nơi mình đi qua.',
    'Sự bình yên trong tâm là món quà lớn nhất ta có thể trao tặng cho những người xung quanh.',
    'Hãy để lòng từ bi trở thành ánh sáng dẫn lối cho những tâm hồn đang lạc lối.',
    'Người sống chánh niệm sẽ tìm thấy ý nghĩa trong cả những công việc nhỏ nhặt nhất.',
    'Đừng để nỗi buồn của quá khứ phủ bóng lên niềm vui của hiện tại.',
    'Hãy tu dưỡng tâm hồn để mỗi ngày trôi qua đều nhẹ nhàng và an lạc hơn.',
    'Người có lòng từ bi rộng lớn sẽ không phân biệt giữa bạn và thù.',
    'Từ bi, trí tuệ và an lạc chính là ba viên ngọc quý của một tâm hồn tu tập chân chính.',
  ],

  IMOU_APP_ID: 'lcb191950b44ba4663',
  IMOU_APP_SECRET: '5d9507d2aa7e41a2b615268361d5cb',
  IMOU_DATA_CENTER: 'or',
  IMOU_CAMERAS: {
    'fresh': '32770CAPBVB6A5B',
    'thu ngan': 'C1141CAPBV8CF20',
    'thu ngân': 'C1141CAPBV8CF20',
    'fmcg': 'B69B7BJPSFB5BFC',
  },
};
