// config.js
module.exports = {
      TRIGGER_KEYWORD: 'báo cáo',
      ACTUAL_KEYWORD: 'doanh thu hiện tại',

      FRESH_INDUSTRIES: ['Rau Củ Quả CL', 'Cá (Hải sản)', 'Thịt', 'Trứng', 'Trái cây'],

      DAYS_IN_TARGET_MONTH: 31,

      LABEL_PREV_MONTH: 'Tháng 7',
      LABEL_CURR_MONTH: 'Tháng 8 (dự kiến)',

      GOOGLE_SHEET_ID: '1wQlsrIsXTAwWByZwmfOs3f4Hsuh9TmLdWHg_1ECMttE',

      TAB_GIDS: {
              revenuePrevMonth: '0',
              revenueCurrMonth: '1560618412',
              volumePrevMonth: '1085666896',
              volumeCurrMonth: '594018980',
      },

      TARGET_GROUP_ID: 'Cf36a100a627b9eafdd7c5e87fe3a88a6',
      CRON_SECRET: 'kesach2026secret',
      SCHEDULED_MESSAGES: {
              '1': 'Chào ngày mới Anh Chị, Chúc Anh Chị làm việc vui vẻ !\nNhớ Selfie đúng giờ nhé !',
              '2': 'Mình nhớ báo cáo Nhập Aba, Nhập Fresh, Kiểm Date, Kiểm Kê, In Tem Giá, Các công việc cơ bản trước 8h nhé !',
              '3': 'Mình có công việc báo cáo Fresh vào lúc 10h , Anh Chị nhớ hoàn tất nhé !',
              '4': 'Mình có công việc báo cáo Fresh vào nhóm siêu thị vào lúc 12h, Các nhóm Thu Ngân-Fresh Khu vực vào khung giờ này cũng cần báo cáo, Anh Chị nhớ hoàn tất nhé !',
              '5': 'Mình có công việc báo cáo Nộp Tiền trước 14h, Anh Chị nhớ hoàn tất nhé !',
              '6': 'Mình có công việc báo cáo Fresh vào lúc 14h, Anh Chị nhớ hoàn tất nhé !',
              '7': 'Mình có công việc báo cáo Fresh vào lúc 16h, Anh Chị nhớ hoàn tất nhé !',
              '8': 'Mình có các công việc cuối ngày: Báo cáo trưng bày hàng hóa các Kv phụ trách-Kiểm tra lại Tool công việc siêu thị ! GO GO chuẩn bị về với Gia Đình thoi nào !!!!!',
              '9': 'Chúc Anh Chị Ngủ Ngon! Nghĩ ngơi sớm nhé !',
      },

      DAY_LABELS: ['Chủ Nhật', 'Thứ 2', 'Thứ 3', 'Thứ 4', 'Thứ 5', 'Thứ 6', 'Thứ 7'],

      CLEANING_SCHEDULE: {
              0: ['Xuyên'],
              1: ['Biển'],
              2: ['Mai', 'Thi (Vệ sinh kho)', 'Vui/Ngọc (Trần nhà, Áp kính)'],
              3: ['Thư'],
              4: ['Tiên', 'Thi (Vệ sinh kho)', 'Vui/Ngọc (Trần nhà, Áp kính)'],
              5: ['Oanh'],
              6: ['Trường', 'Thi (Vệ sinh kho)', 'Vui/Ngọc (Trần nhà, Áp kính)'],
      },

      WEATHER_LOCATION: 'Soc+Trang',

      LIFE_QUOTES: [
              'Hãy sống mỗi ngày như thể đó là ngày cuối cùng, và học hỏi như thể sẽ sống mãi mãi.',
              'Cuộc sống không phải là chờ đợi cơn bão đi qua, mà là học cách nhảy múa dưới mưa.',
              'Hạnh phúc không phải là đích đến, mà là cách chúng ta đi trên hành trình đó.',
              'Mỗi buổi sáng là một cơ hội mới để bắt đầu lại và làm tốt hơn hôm qua.',
              'Nụ cười của bạn hôm nay có thể là ánh sáng dẫn đường cho ai đó.',
              'Đừng đếm những ngày trôi qua, hãy làm cho những ngày đó trở nên đáng giá.',
              'Thành công không phải là điểm cuối, thất bại không phải là kết thúc, quan trọng là sự dũng cảm để tiếp tục.',
              'Cuộc sống tươi đẹp hơn khi ta biết ơn những điều nhỏ bé quanh mình.',
              'Làm việc chăm chỉ hôm nay, để ngày mai được mỉm cười.',
              'Yêu thương những gì mình làm, mọi việc sẽ trở nên nhẹ nhàng hơn.',
              'Người thành công không phải người chưa từng vấp ngã, mà là người luôn đứng dậy sau mỗi lần vấp ngã.',
              'Đừng chờ đợi cơ hội, hãy tự mình tạo ra nó bằng chính sự chăm chỉ mỗi ngày.',
              'Một tinh thần lạc quan sẽ biến khó khăn thành cơ hội để trưởng thành.',
              'Gia đình là nơi bắt đầu mọi niềm vui và là bến đỗ bình yên sau mỗi ngày làm việc.',
              'Bí quyết để tiến xa là bắt đầu ngay từ hôm nay, dù chỉ là một bước nhỏ.',
              'Kỷ luật bản thân hôm nay chính là món quà bạn tặng cho chính mình ngày mai.',
              'Đừng sợ đi chậm, chỉ sợ đứng yên không tiến bước.',
              'Mỗi khó khăn đều mang theo một bài học, hãy đón nhận nó bằng nụ cười.',
              'Sự tử tế không tốn kém gì cả, nhưng giá trị của nó là vô giá.',
              'Người biết ơn là người luôn tìm thấy hạnh phúc dù trong hoàn cảnh nào.',
              'Thái độ tích cực chính là chìa khóa mở ra mọi cánh cửa thành công.',
              'Hãy làm việc bằng cả trái tim, thành quả sẽ tự nhiên đến.',
              'Không có con đường nào dẫn đến thành công mà không có mồ hôi và nỗ lực.',
              'Sống chậm lại một chút để cảm nhận những điều tốt đẹp quanh mình.',
              'Mỗi lần cố gắng, dù nhỏ, đều đưa bạn đến gần hơn với ước mơ.',
              'Niềm tin vào bản thân là nền tảng vững chắc nhất cho mọi thành công.',
              'Đoàn kết là sức mạnh, cùng nhau chúng ta sẽ đi được xa hơn.',
              'Hãy biến áp lực thành động lực để bứt phá mỗi ngày.',
              'Sự chân thành luôn được đền đáp bằng lòng tin và sự yêu mến.',
              'Ngày hôm nay là món quà, đó là lý do vì sao nó được gọi là hiện tại.',
              'Càng khó khăn, càng phải giữ vững tinh thần và nụ cười trên môi.',
              'Người mạnh mẽ không phải người không bao giờ khóc, mà là người biết đứng dậy sau nước mắt.',
              'Hãy trân trọng những gì mình đang có, vì đó là điều nhiều người ao ước.',
              'Chỉ cần bạn không bỏ cuộc, mọi cố gắng đều sẽ được đền đáp xứng đáng.',
              'Một ngày làm việc vui vẻ sẽ mang lại một đêm ngủ ngon và một ngày mai tươi sáng.',
              'Trách nhiệm và đam mê là hai đôi cánh giúp bạn bay cao trong công việc.',
              'Đừng so sánh mình với người khác, hãy so sánh mình hôm nay với chính mình hôm qua.',
              'Sự tận tâm trong công việc nhỏ sẽ mở đường cho những cơ hội lớn.',
              'Hãy luôn giữ cho mình một trái tim ấm áp giữa cuộc sống bộn bề.',
              'Niềm vui lớn nhất là khi thấy nỗ lực của mình mang lại giá trị cho người khác.',
              'Cuộc sống sẽ thưởng cho những ai kiên trì đến cùng.',
              'Một nụ cười chân thành có thể xoa dịu cả một ngày mệt mỏi.',
              'Hãy làm việc như thể không ai đang nhìn, và sống như thể mỗi ngày là món quà.',
              'Sự khiêm tốn và chăm chỉ luôn là nền tảng của những thành công bền vững.',
              'Đừng để nỗi sợ hãi ngăn cản bạn thử những điều mới mẻ.',
              'Mỗi sáng thức dậy là một cơ hội để viết tiếp câu chuyện đẹp của đời mình.',
              'Thành công không đến từ may mắn, mà đến từ sự chuẩn bị gặp cơ hội.',
              'Hãy đối xử với mọi người bằng sự tôn trọng, dù ở bất kỳ vị trí nào.',
              'Sự kiên nhẫn là chìa khóa để biến những điều không thể thành có thể.',
              'Một tập thể đoàn kết có thể vượt qua mọi thử thách khó khăn nhất.',
            ],

              HEALTH_TIPS: [
                        'Hạn chế dùng điện thoại ít nhất 30 phút trước khi ngủ để mắt và não được nghỉ ngơi.',
                        'Uống một ly nước ấm trước khi ngủ giúp cơ thể thư giãn và dễ đi vào giấc ngủ hơn.',
                        'Tránh ăn quá no hoặc uống cà phê, trà đặc vào buổi tối để có giấc ngủ ngon.',
                        'Giữ phòng ngủ thoáng mát, tối và yên tĩnh sẽ giúp bạn ngủ sâu giấc hơn.',
                        'Dành 5-10 phút hít thở sâu hoặc thiền nhẹ trước khi ngủ giúp giảm căng thẳng.',
                        'Ngủ đủ 7-8 tiếng mỗi đêm giúp cơ thể phục hồi và làm việc hiệu quả hơn vào hôm sau.',
                        'Tránh vận động mạnh sát giờ ngủ, thay vào đó hãy giãn cơ nhẹ nhàng.',
                        'Đi ngủ và thức dậy đúng giờ mỗi ngày giúp đồng hồ sinh học ổn định hơn.',
                        'Tắt bớt đèn sáng và ánh sáng xanh trước khi ngủ để cơ thể sản sinh melatonin tốt hơn.',
                        'Một tách trà thảo mộc ấm (không chứa caffeine) có thể giúp bạn thư giãn trước khi ngủ.',
                        'Viết ra những điều khiến bạn lo lắng trước khi ngủ để đầu óc nhẹ nhàng hơn.',
                        'Giữ tinh thần thoải mái, buông bỏ muộn phiền trong ngày trước khi lên giường.',
                        'Nệm và gối phù hợp giúp cột sống được nâng đỡ tốt, ngủ ngon hơn.',
                        'Tránh xem tin tức hoặc nội dung gây căng thẳng ngay trước giờ ngủ.',
                        'Massage nhẹ vùng vai gáy giúp thư giãn cơ bắp sau một ngày làm việc.',
                      ],

        IMOU_APP_ID: 'lcb191950b44ba4663',
        IMOU_APP_SECRET: '5d9507d2aa7e41a2b615268361d5cb',
        IMOU_DATA_CENTER: 'or',
        IMOU_CAMERAS: {
                  'fresh': '32770CAPBVB6A5B',
                  'thu ngan': 'C1141CAPBV8CF20',
                  'thu ngân': 'C1141CAPBV8CF20',
                  'fmcg': 'B69B7BJPSFB5BFC',
        },
};
