const https = require('https');
const config = require('./config');

function fetchCsv(gid) {
  const url = 'https://docs.google.com/spreadsheets/d/' + config.GOOGLE_SHEET_ID + '/export?format=csv&gid=' + gid;
    return new Promise((resolve, reject) => {
        https
              .get(url, (res) => {
                      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
                                https
                                            .get(res.headers.location, (res2) => collectBody(res2, resolve, reject))
                                                        .on('error', reject);
                                                                  return;
                                                                          }
                                                                                  if (res.statusCode !== 200) {
                                                                                            reject(new Error('Loi tai Sheet gid=' + gid + ' status=' + res.statusCode));
                                                                                                      return;
                                                                                                              }
                                                                                                                      collectBody(res, resolve, reject);
                                                                                                                            })
                                                                                                                                  .on('error', reject);
                                                                                                                                    });
                                                                                                                                    }
                                                                                                                                    
                                                                                                                                    function collectBody(res, resolve, reject) {
                                                                                                                                      let data = '';
                                                                                                                                        res.setEncoding('utf8');
                                                                                                                                          res.on('data', (chunk) => (data += chunk));
                                                                                                                                            res.on('end', () => resolve(data));
                                                                                                                                              res.on('error', reject);
                                                                                                                                              }
                                                                                                                                              
                                                                                                                                              function parseCsv(text) {
                                                                                                                                                const rows = [];
                                                                                                                                                  let row = [];
                                                                                                                                                    let field = '';
                                                                                                                                                      let inQuotes = false;
                                                                                                                                                      
                                                                                                                                                        for (let i = 0; i < text.length; i++) {
                                                                                                                                                            const c = text[i];
                                                                                                                                                                const next = text[i + 1];
                                                                                                                                                                
                                                                                                                                                                    if (inQuotes) {
                                                                                                                                                                          if (c === '"' && next === '"') {
                                                                                                                                                                                  field += '"';
                                                                                                                                                                                          i++;
                                                                                                                                                                                                } else if (c === '"') {
                                                                                                                                                                                                        inQuotes = false;
                                                                                                                                                                                                              } else {
                                                                                                                                                                                                                      field += c;
                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                      if (c === '"') {
                                                                                                                                                                                                                                              inQuotes = true;
                                                                                                                                                                                                                                                    } else if (c === ',') {
                                                                                                                                                                                                                                                            row.push(field);
                                                                                                                                                                                                                                                                    field = '';
                                                                                                                                                                                                                                                                          } else if (c === '\n') {
                                                                                                                                                                                                                                                                                  row.push(field);
                                                                                                                                                                                                                                                                                          rows.push(row);
                                                                                                                                                                                                                                                                                                  row = [];
                                                                                                                                                                                                                                                                                                          field = '';
                                                                                                                                                                                                                                                                                                                } else if (c === '\r') {
                                                                                                                                                                                                                                                                                                                      } else {
                                                                                                                                                                                                                                                                                                                              field += c;
                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                            if (field.length || row.length) {
                                                                                                                                                                                                                                                                                                                                                row.push(field);
                                                                                                                                                                                                                                                                                                                                                    rows.push(row);
                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                        return rows;
                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                        function parseVNNumber(raw) {
                                                                                                                                                                                                                                                                                                                                                          if (raw == null) return null;
                                                                                                                                                                                                                                                                                                                                                            let s = String(raw).trim();
                                                                                                                                                                                                                                                                                                                                                              if (s === '') return null;
                                                                                                                                                                                                                                                                                                                                                                s = s.replace(/\s/g, '');
                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                  const hasComma = s.includes(',');
                                                                                                                                                                                                                                                                                                                                                                    const hasDot = s.includes('.');
                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                      if (hasComma && hasDot) {
                                                                                                                                                                                                                                                                                                                                                                          if (s.lastIndexOf(',') > s.lastIndexOf('.')) {
                                                                                                                                                                                                                                                                                                                                                                                s = s.replace(/\./g, '').replace(',', '.');
                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                          s = s.replace(/,/g, '');
                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                } else if (hasComma) {
                                                                                                                                                                                                                                                                                                                                                                                                    const parts = s.split(',');
                                                                                                                                                                                                                                                                                                                                                                                                        if (parts.length > 2) {
                                                                                                                                                                                                                                                                                                                                                                                                              s = parts.join('');
                                                                                                                                                                                                                                                                                                                                                                                                                  } else {
                                                                                                                                                                                                                                                                                                                                                                                                                        s = s.replace(',', '.');
                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                              } else if (hasDot) {
                                                                                                                                                                                                                                                                                                                                                                                                                                  const parts = s.split('.');
                                                                                                                                                                                                                                                                                                                                                                                                                                      if (parts.length > 2) {
                                                                                                                                                                                                                                                                                                                                                                                                                                            s = parts.join('');
                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                    const num = parseFloat(s);
                                                                                                                                                                                                                                                                                                                                                                                                                                                      return isNaN(num) ? null : num;
                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                      async function fetchSheetRows(gid) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        const csvText = await fetchCsv(gid);
                                                                                                                                                                                                                                                                                                                                                                                                                                                          const rows = parseCsv(csvText);
                                                                                                                                                                                                                                                                                                                                                                                                                                                            return rows.slice(1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                            module.exports = { fetchSheetRows, parseVNNumber };
